### ISSUE TITLE
Random curl errors

### ISSUE THREAD

**Issue by ibreakshit** [dusterio/laravel-aws-worker#3]
I've been running into this error from time to time. Error seems to be an error related to ssl certs but unclear how to handle it.

Maybe there should be an option to switch off ssl validation? Just FYI.

```
[2016-08-26 20:01:30] lumen.ERROR: GuzzleHttp\Exception\RequestException: cURL error 77:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187
Stack trace:
#0 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 newrelic/Guzzle6(1): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /var/app/current/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(72): newrelic\Guzzle6\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#7 /var/app/current/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#8 /var/app/current/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(68): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#9 /var/app/current/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#10 /var/app/current/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#11 /var/app/current/vendor/guzzlehttp/guzzle/src/Client.php(275): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#12 /var/app/current/vendor/guzzlehttp/guzzle/src/Client.php(123): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#13 /var/app/current/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->requestAsync('post', Object(GuzzleHttp\Psr7\Uri), Array)
#14 /var/app/current/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('post', 'https://mandril...', Array)
#15 /var/app/current/vendor/illuminate/mail/Transport/MandrillTransport.php(57): GuzzleHttp\Client->__call('post', Array)
#16 /var/app/current/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(85): Illuminate\Mail\Transport\MandrillTransport->send(Object(Swift_Message), Array)
#17 /var/app/current/vendor/illuminate/mail/Mailer.php(385): Swift_Mailer->send(Object(Swift_Message), Array)
#18 /var/app/current/vendor/illuminate/mail/Mailer.php(171): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#19 /var/app/current/vendor/illuminate/mail/Mailer.php(276): Illuminate\Mail\Mailer->send('emails.retarget...', Array, Object(Closure))
#20 /var/app/current/vendor/illuminate/queue/Jobs/Job.php(130): Illuminate\Mail\Mailer->handleQueuedMessage(Object(Dusterio\AwsWorker\Jobs\AwsJob), Array)
#21 /var/app/current/vendor/dusterio/laravel-aws-worker/src/Jobs/AwsJob.php(41): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#22 /var/app/current/vendor/illuminate/queue/Worker.php(213): Dusterio\AwsWorker\Jobs\AwsJob->fire()
#23 /var/app/current/vendor/dusterio/laravel-aws-worker/src/Controllers/WorkerController.php(81): Illuminate\Queue\Worker->process('awseb-e-6ux2r39...', Object(Dusterio\AwsWorker\Jobs\AwsJob), 0, 0)
#24 [internal function]: Dusterio\AwsWorker\Controllers\WorkerController->queue(Object(Illuminate\Http\Request), Object(Illuminate\Queue\Worker), Object(Laravel\Lumen\Application))
#25 /var/app/current/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#26 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(593): Illuminate\Container\Container->call(Array, Array)
#27 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(536): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#28 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(501): Laravel\Lumen\Application->callControllerAction(Array)
#29 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(486): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#30 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#31 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(636): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#32 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#33 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(NULL)
#34 /var/app/current/public/index.php(28): Laravel\Lumen\Application->run()
#35 {main}

Next Dusterio\AwsWorker\Exceptions\FailedJobException: Worker failed executing the job in /var/app/current/vendor/dusterio/laravel-aws-worker/src/Controllers/WorkerController.php:84
Stack trace:
#0 [internal function]: Dusterio\AwsWorker\Controllers\WorkerController->queue(Object(Illuminate\Http\Request), Object(Illuminate\Queue\Worker), Object(Laravel\Lumen\Application))
#1 /var/app/current/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#2 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(593): Illuminate\Container\Container->call(Array, Array)
#3 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(536): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#4 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(501): Laravel\Lumen\Application->callControllerAction(Array)
#5 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(486): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#6 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#7 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(636): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#8 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#9 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(NULL)
#10 /var/app/current/public/index.php(28): Laravel\Lumen\Application->run()
#11 {main}  
[2016-08-26 20:01:30] lumen.ERROR: GuzzleHttp\Exception\RequestException: cURL error 77:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187
Stack trace:
#0 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 newrelic/Guzzle6(1): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /var/app/current/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(72): newrelic\Guzzle6\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#7 /var/app/current/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#8 /var/app/current/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(68): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#9 /var/app/current/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#10 /var/app/current/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#11 /var/app/current/vendor/guzzlehttp/guzzle/src/Client.php(275): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#12 /var/app/current/vendor/guzzlehttp/guzzle/src/Client.php(123): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#13 /var/app/current/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->requestAsync('post', Object(GuzzleHttp\Psr7\Uri), Array)
#14 /var/app/current/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('post', 'https://mandril...', Array)
#15 /var/app/current/vendor/illuminate/mail/Transport/MandrillTransport.php(57): GuzzleHttp\Client->__call('post', Array)
#16 /var/app/current/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(85): Illuminate\Mail\Transport\MandrillTransport->send(Object(Swift_Message), Array)
#17 /var/app/current/vendor/illuminate/mail/Mailer.php(385): Swift_Mailer->send(Object(Swift_Message), Array)
#18 /var/app/current/vendor/illuminate/mail/Mailer.php(171): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#19 /var/app/current/vendor/illuminate/mail/Mailer.php(276): Illuminate\Mail\Mailer->send('emails.retarget...', Array, Object(Closure))
#20 /var/app/current/vendor/illuminate/queue/Jobs/Job.php(130): Illuminate\Mail\Mailer->handleQueuedMessage(Object(Dusterio\AwsWorker\Jobs\AwsJob), Array)
#21 /var/app/current/vendor/dusterio/laravel-aws-worker/src/Jobs/AwsJob.php(41): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#22 /var/app/current/vendor/illuminate/queue/Worker.php(213): Dusterio\AwsWorker\Jobs\AwsJob->fire()
#23 /var/app/current/vendor/dusterio/laravel-aws-worker/src/Controllers/WorkerController.php(81): Illuminate\Queue\Worker->process('awseb-e-6ux2r39...', Object(Dusterio\AwsWorker\Jobs\AwsJob), 0, 0)
#24 [internal function]: Dusterio\AwsWorker\Controllers\WorkerController->queue(Object(Illuminate\Http\Request), Object(Illuminate\Queue\Worker), Object(Laravel\Lumen\Application))
#25 /var/app/current/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#26 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(593): Illuminate\Container\Container->call(Array, Array)
#27 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(536): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#28 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(501): Laravel\Lumen\Application->callControllerAction(Array)
#29 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(486): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#30 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#31 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(636): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#32 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#33 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(NULL)
#34 /var/app/current/public/index.php(28): Laravel\Lumen\Application->run()
#35 {main}

Next Dusterio\AwsWorker\Exceptions\FailedJobException: Worker failed executing the job in /var/app/current/vendor/dusterio/laravel-aws-worker/src/Controllers/WorkerController.php:84
Stack trace:
#0 [internal function]: Dusterio\AwsWorker\Controllers\WorkerController->queue(Object(Illuminate\Http\Request), Object(Illuminate\Queue\Worker), Object(Laravel\Lumen\Application))
#1 /var/app/current/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#2 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(593): Illuminate\Container\Container->call(Array, Array)
#3 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(536): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#4 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(501): Laravel\Lumen\Application->callControllerAction(Array)
#5 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(486): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#6 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#7 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(636): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#8 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#9 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(NULL)
#10 /var/app/current/public/index.php(28): Laravel\Lumen\Application->run()
#11 {main}  
```

**Comment by dusterio** [comment]
Hi!

According to the trace, it seems that it's your job, and to be exact, your mailer that causes this error – some SSL settings are perhaps missing, and Mandrill needs those. 

I would say with 99% confidence that this is not related to this package

**Comment by ibreakshit** [comment]
I apologize. I'm using the default Mail packaged with Laravel 5.2 (I'm on lumen 5.2) Illuminate\Mail\MailServiceProvider using the default Mandrill driver. I'll take it up with them, thanks!

**Comment by ibreakshit** [comment]
Just in case: https://laracasts.com/discuss/channels/laravel/random-curl-error-77-mail-mandrill-driver-aws-sqs
