### ISSUE TITLE
Support for Lumen 5.3?

### ISSUE THREAD

**Issue by ibreakshit** [dusterio/laravel-aws-worker#4]
Hey, it's me again, sorry to bug you again but I seem to have trouble with getting the worker work with Lumen 5.3.

This is the error I'm seeing

```
[2016-09-12 22:51:18] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 3 passed to Illuminate\Queue\Worker::process() must be an instance of Illuminate\Queue\WorkerOptions, integer given, called in /var/app/current/vendor/dusterio/laravel-aws-worker/src/Controllers/WorkerController.php on line 81 in /var/app/current/vendor/illuminate/queue/Worker.php:199
Stack trace:
#0 /var/app/current/vendor/dusterio/laravel-aws-worker/src/Controllers/WorkerController.php(81): Illuminate\Queue\Worker->process('awseb-e-ptip9yx...', Object(Dusterio\AwsWorker\Jobs\AwsJob), 0, 0)
#1 [internal function]: Dusterio\AwsWorker\Controllers\WorkerController->queue(Object(Illuminate\Http\Request), Object(Illuminate\Queue\Worker), Object(Laravel\Lumen\Application))
#2 /var/app/current/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#3 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(610): Illuminate\Container\Container->call(Array, Array)
#4 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(553): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#5 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(512): Laravel\Lumen\Application->callControllerAction(Array)
#6 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(497): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#7 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(394): Laravel\Lumen\Application->handleFoundRoute(Array)
#8 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(650): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#9 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(400): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#10 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(341): Laravel\Lumen\Application->dispatch(NULL)
#11 /var/app/current/public/index.php(28): Laravel\Lumen\Application->run()
#12 {main}  
```

I've downgraded to Lumen 5.2 for now.
Thanks.

**Comment by dusterio** [comment]
Thanks for noticing - I will fix this shotly

**Comment by dusterio** [comment]
This should be ok now - I've tested in Lumen and Laravel both
